### ISSUE TITLE
Browser Implementation and installation

### ISSUE THREAD

**Issue by upuxaa** [Mathieu2301/TradingView-API#161]
**Is your feature request related to a problem? Please describe.**
I am trying to install this library in my react app project, but I realize there are limitations due to the npm modules used like https, os, ws.

**Describe the solution you'd like**
I would love to be able to use this on the browser side instead of a node.js environment.

**Describe alternatives you've considered**
Maybe a solution would be able to detect if it is a client side project when a npm install occurs (a hook), and can use different modules to request data.

**Additional context**
Having a server to send data can be costly 😅

**Comment by upuxaa** [comment]
Hey I thought of another solution; what if replace the request library with fetch, and use a require statement to dynamically switch between fetch and node-fetch; it will be the same type interface interchangable

**Comment by Mathieu2301** [comment]
It simply won't work because of the origin of the request.

### On tradingview.com
<img width="765" alt="Capture d’écran 2022-11-27 à 20 43 25" src="https://user-images.githubusercontent.com/21021423/204156381-c8d71160-c8e0-4157-a255-0e22ac50380e.png">

### On any other website
<img width="885" alt="Capture d’écran 2022-11-27 à 20 42 43" src="https://user-images.githubusercontent.com/21021423/204156342-713ffdec-d0e4-4614-83a1-ceb154a88d69.png">

**Comment by Mathieu2301** [comment]
Even with `widgetdata.tradingview.com`. TradingView simply forbids it.

**Comment by Manas-Nagelia** [comment]
In Next.js, I'm having a similar problem. I need to figure out how to pass the real-time data from server side to client-side, without causing any errors. Simply returning the value on the `onUpdate()` function does not work, and I cannot have it run client side. My best option is to pass the data into some database and have the client fetch it from the database.
